- hosts: all
  tasks:
  - name: Sort by Operating System
    group_by: key={{ansible_distribution}}
      
- hosts: MacOSX
  gather_facts: False
  vars:
    dist: apache-ant-1.9.4
    package: "{{ dist }}-bin.tar.bz2"
    package_url: "http://www.carfab.com/apachesoftware//ant/binaries/{{ package }}"
  sudo: yes
  tasks:
    - name: download {{ package }}
      get_url: url={{ package_url }} dest=/tmp/{{ package }} mode=0644
    - name: Layout structure
      file: state=directory path=/opt/apache  owner=root group=admin
    - name: Unpack {{ package }}
      unarchive: src=/tmp/{{ package }} dest=/opt/apache
    - name: Create default link to {{ dist }}
      file: state=link src=/opt/apache/{{ dist }} dest=/opt/apache/ant
    - name: Clean up
      file: path=/tmp/{{ package }} state=absent
    