---
- hosts: all
  tasks:
  - name: Sort by Operating System
    group_by: key={{ansible_distribution}}
      
- hosts: MacOSX
  gather_facts: False
  vars:
    dist: bash-92
    package: "{{ dist }}.tar.gz"
    package_url: "https://opensource.apple.com/tarballs/bash/{{package}}"
  sudo: yes
  tasks:
  - name: download {{ package }}
    get_url: url={{ package_url }} dest=/tmp/{{ package }} mode=0644  
  - name: unpack {{ package }}
    unarchive: src=/tmp/{{ package }} dest=/tmp 
  - name: Get patch
    get_url: url=https://ftp.gnu.org/pub/gnu/bash/bash-3.2-patches/bash32-052 dest=/tmp/bash32-052
  - name: Apply patch
    shell: patch -p0 < /tmp/bash32-052 chdir=/tmp/{{dist}}/bash-3.2
  - name: Build
    command: xcodebuild chdir=/tmp/{{ dist }}
  - name: Install
    copy: src=/tmp/{{dist}}/build/Release/{{item}} dest=/bin/{{item}} mode=777 owner=root group=wheel force=yes
    with_items:
      - bash
      - sh
  - name: Clean up {{ package }}
    file: path=/tmp/{{ package }} state=absent
  - name: Clean up {{ dist }}
    file: path=/tmp/{{ dist }} state=absent
  - name: Clean up bash32-052
    file: path=/tmp/bash32-052 state=absent

