---
- hosts: all
  tasks:
  - name: Sort by Operating System
    group_by: key={{ansible_distribution}}
    
- hosts: MacOSX
  gather_facts: False
  sudo: yes
  vars: 
    package: XQuartz.pkg
    package_url: "https://dl.dropboxusercontent.com/u/2377323/{{ package }}"
  tasks:
    - name: download {{ package }}
      get_url: url={{ package_url }} dest=/tmp/{{ package }} mode=0644    
    - name: Run installer
      command: installer -package /tmp/{{ package }} -target /
    - name: Clean up
      file: path=/tmp/{{ package }} state=absent

